name: CI_Tp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: 
          pip install -r requirements.txt

      - name: Lint code with flake8
        run: 
          flake8 app --count --select=E9,F63,F7,F82,F841 --show-source  --statistics 
          flake8 app --count --max-comlexity=10 --max-line-length=127 --show-source  --statistics 
          flake8 tests --count --max-line-length=127 --statistics
      - name : lancer les tests
        run: 
        pytest -v --cv=app     